# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.modules_api import ModulesApi  # noqa: E501


class TestModulesApi(unittest.TestCase):
    """ModulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModulesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_add_module_issues(self) -> None:
        """Test case for add_module_issues

        Add module issues  # noqa: E501
        """
        pass

    def test_archive_module(self) -> None:
        """Test case for archive_module

        Archive module  # noqa: E501
        """
        pass

    def test_create_module(self) -> None:
        """Test case for create_module

        Create module  # noqa: E501
        """
        pass

    def test_delete_module(self) -> None:
        """Test case for delete_module

        Delete module  # noqa: E501
        """
        pass

    def test_delete_module_issue(self) -> None:
        """Test case for delete_module_issue

        Delete module issue  # noqa: E501
        """
        pass

    def test_get_archived_modules(self) -> None:
        """Test case for get_archived_modules

        Get archived modules  # noqa: E501
        """
        pass

    def test_get_module(self) -> None:
        """Test case for get_module

        Get module  # noqa: E501
        """
        pass

    def test_get_module2(self) -> None:
        """Test case for get_module2

        Get module  # noqa: E501
        """
        pass

    def test_get_module_issues(self) -> None:
        """Test case for get_module_issues

        Get module issues  # noqa: E501
        """
        pass

    def test_unarchive_module(self) -> None:
        """Test case for unarchive_module

        Unarchive module  # noqa: E501
        """
        pass

    def test_update_module(self) -> None:
        """Test case for update_module

        Update module  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
