# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.work_items_api import WorkItemsApi  # noqa: E501


class TestWorkItemsApi(unittest.TestCase):
    """WorkItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkItemsApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_issue_comment(self) -> None:
        """Test case for create_issue_comment

        Create an issue comment  # noqa: E501
        """
        pass

    def test_create_issue_link(self) -> None:
        """Test case for create_issue_link

        Create an issue link  # noqa: E501
        """
        pass

    def test_create_work_item(self) -> None:
        """Test case for create_work_item

        Create an work item  # noqa: E501
        """
        pass

    def test_delete_issue_attachment(self) -> None:
        """Test case for delete_issue_attachment

        Delete an issue attachment  # noqa: E501
        """
        pass

    def test_delete_issue_comment(self) -> None:
        """Test case for delete_issue_comment

        Delete an issue comment  # noqa: E501
        """
        pass

    def test_delete_issue_link(self) -> None:
        """Test case for delete_issue_link

        Delete an issue link  # noqa: E501
        """
        pass

    def test_delete_work_item(self) -> None:
        """Test case for delete_work_item

        Delete an work item  # noqa: E501
        """
        pass

    def test_get_issue_activities(self) -> None:
        """Test case for get_issue_activities

        Get issue activities  # noqa: E501
        """
        pass

    def test_get_issue_activities2(self) -> None:
        """Test case for get_issue_activities2

        Get issue activities  # noqa: E501
        """
        pass

    def test_get_issue_attachment(self) -> None:
        """Test case for get_issue_attachment

        Get an issue attachment  # noqa: E501
        """
        pass

    def test_get_issue_attachment2(self) -> None:
        """Test case for get_issue_attachment2

        Get issue attachment  # noqa: E501
        """
        pass

    def test_get_issue_attachment3(self) -> None:
        """Test case for get_issue_attachment3

        Get an issue attachment  # noqa: E501
        """
        pass

    def test_get_issue_comments(self) -> None:
        """Test case for get_issue_comments

        Get issue comments  # noqa: E501
        """
        pass

    def test_get_issue_comments2(self) -> None:
        """Test case for get_issue_comments2

        Get issue comments  # noqa: E501
        """
        pass

    def test_get_issue_links(self) -> None:
        """Test case for get_issue_links

        Get issue links  # noqa: E501
        """
        pass

    def test_get_issue_links2(self) -> None:
        """Test case for get_issue_links2

        Get issue links  # noqa: E501
        """
        pass

    def test_get_work_item(self) -> None:
        """Test case for get_work_item

        Work Item retrieve endpoints  # noqa: E501
        """
        pass

    def test_get_work_item2(self) -> None:
        """Test case for get_work_item2

        Work Item retrieve endpoints  # noqa: E501
        """
        pass

    def test_patch_work_item(self) -> None:
        """Test case for patch_work_item

        Patch an work item  # noqa: E501
        """
        pass

    def test_update_issue_comment(self) -> None:
        """Test case for update_issue_comment

        Update an issue comment  # noqa: E501
        """
        pass

    def test_update_issue_link(self) -> None:
        """Test case for update_issue_link

        Update an issue link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
