# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.create_cycle_request import CreateCycleRequest  # noqa: E501

class TestCreateCycleRequest(unittest.TestCase):
    """CreateCycleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCycleRequest:
        """Test CreateCycleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCycleRequest`
        """
        model = CreateCycleRequest()  # noqa: E501
        if include_optional:
            return CreateCycleRequest(
                name = 'Cycle 1',
                description = 'This is a cycle description',
                start_date = '2025-01-01T00:00Z',
                end_date = '2025-01-01T00:00Z'
            )
        else:
            return CreateCycleRequest(
                name = 'Cycle 1',
        )
        """

    def testCreateCycleRequest(self):
        """Test CreateCycleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
