# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.assets_api import AssetsApi  # noqa: E501


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_create_generic_asset_upload(self) -> None:
        """Test case for create_generic_asset_upload

        Create Assets  # noqa: E501
        """
        pass

    def test_create_generic_asset_upload2(self) -> None:
        """Test case for create_generic_asset_upload2

        Create Assets  # noqa: E501
        """
        pass

    def test_create_user_asset_upload(self) -> None:
        """Test case for create_user_asset_upload

        Create User Assets  # noqa: E501
        """
        pass

    def test_create_user_asset_upload2(self) -> None:
        """Test case for create_user_asset_upload2

        Create User Assets  # noqa: E501
        """
        pass

    def test_create_user_server_asset_upload(self) -> None:
        """Test case for create_user_server_asset_upload

        Create Server  # noqa: E501
        """
        pass

    def test_create_user_server_asset_upload2(self) -> None:
        """Test case for create_user_server_asset_upload2

        Create Server  # noqa: E501
        """
        pass

    def test_delete_user_asset(self) -> None:
        """Test case for delete_user_asset

        Delete User Assets  # noqa: E501
        """
        pass

    def test_delete_user_asset2(self) -> None:
        """Test case for delete_user_asset2

        Delete User Assets  # noqa: E501
        """
        pass

    def test_delete_user_server_asset(self) -> None:
        """Test case for delete_user_server_asset

        Delete Server  # noqa: E501
        """
        pass

    def test_delete_user_server_asset2(self) -> None:
        """Test case for delete_user_server_asset2

        Delete Server  # noqa: E501
        """
        pass

    def test_get_generic_asset(self) -> None:
        """Test case for get_generic_asset

        Retrieve Assets  # noqa: E501
        """
        pass

    def test_get_generic_asset2(self) -> None:
        """Test case for get_generic_asset2

        Retrieve Assets  # noqa: E501
        """
        pass

    def test_update_generic_asset(self) -> None:
        """Test case for update_generic_asset

        Update Assets  # noqa: E501
        """
        pass

    def test_update_generic_asset2(self) -> None:
        """Test case for update_generic_asset2

        Update Assets  # noqa: E501
        """
        pass

    def test_update_user_asset(self) -> None:
        """Test case for update_user_asset

        Update User Assets  # noqa: E501
        """
        pass

    def test_update_user_asset2(self) -> None:
        """Test case for update_user_asset2

        Update User Assets  # noqa: E501
        """
        pass

    def test_update_user_server_asset(self) -> None:
        """Test case for update_user_server_asset

        Update Server  # noqa: E501
        """
        pass

    def test_update_user_server_asset2(self) -> None:
        """Test case for update_user_server_asset2

        Update Server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
