# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.get_issue_attachment2_request import GetIssueAttachment2Request  # noqa: E501

class TestGetIssueAttachment2Request(unittest.TestCase):
    """GetIssueAttachment2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetIssueAttachment2Request:
        """Test GetIssueAttachment2Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetIssueAttachment2Request`
        """
        model = GetIssueAttachment2Request()  # noqa: E501
        if include_optional:
            return GetIssueAttachment2Request(
                name = '',
                type = '',
                size = 56,
                external_id = '',
                external_source = ''
            )
        else:
            return GetIssueAttachment2Request(
        )
        """

    def testGetIssueAttachment2Request(self):
        """Test GetIssueAttachment2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
