# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_archive_project(self) -> None:
        """Test case for archive_project

        Archive Project  # noqa: E501
        """
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete Project  # noqa: E501
        """
        pass

    def test_list_projects(self) -> None:
        """Test case for list_projects

        List Projects  # noqa: E501
        """
        pass

    def test_list_projects2(self) -> None:
        """Test case for list_projects2

        List Projects  # noqa: E501
        """
        pass

    def test_unarchive_project(self) -> None:
        """Test case for unarchive_project

        Unarchive Project  # noqa: E501
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
