# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.cycle import Cycle  # noqa: E501

class TestCycle(unittest.TestCase):
    """Cycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cycle:
        """Test Cycle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cycle`
        """
        model = Cycle()  # noqa: E501
        if include_optional:
            return Cycle(
                id = '',
                total_issues = 56,
                cancelled_issues = 56,
                completed_issues = 56,
                started_issues = 56,
                unstarted_issues = 56,
                backlog_issues = 56,
                total_estimates = 1.337,
                completed_estimates = 1.337,
                started_estimates = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                description = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                view_props = None,
                sort_order = 1.337,
                external_source = '',
                external_id = '',
                progress_snapshot = None,
                archived_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                logo_props = None,
                timezone = 'Africa/Abidjan',
                version = -2147483648,
                created_by = '',
                updated_by = '',
                project = '',
                workspace = '',
                owned_by = ''
            )
        else:
            return Cycle(
                id = '',
                total_issues = 56,
                cancelled_issues = 56,
                completed_issues = 56,
                started_issues = 56,
                unstarted_issues = 56,
                backlog_issues = 56,
                total_estimates = 1.337,
                completed_estimates = 1.337,
                started_estimates = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                created_by = '',
                updated_by = '',
                project = '',
                workspace = '',
                owned_by = '',
        )
        """

    def testCycle(self):
        """Test Cycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
