# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.search_issues200_response_issues_inner import SearchIssues200ResponseIssuesInner  # noqa: E501

class TestSearchIssues200ResponseIssuesInner(unittest.TestCase):
    """SearchIssues200ResponseIssuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchIssues200ResponseIssuesInner:
        """Test SearchIssues200ResponseIssuesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchIssues200ResponseIssuesInner`
        """
        model = SearchIssues200ResponseIssuesInner()  # noqa: E501
        if include_optional:
            return SearchIssues200ResponseIssuesInner(
                name = '',
                id = '',
                sequence_id = '',
                project__identifier = '',
                project_id = '',
                workspace__slug = ''
            )
        else:
            return SearchIssues200ResponseIssuesInner(
        )
        """

    def testSearchIssues200ResponseIssuesInner(self):
        """Test SearchIssues200ResponseIssuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
