# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.patched_generic_asset_update import PatchedGenericAssetUpdate  # noqa: E501

class TestPatchedGenericAssetUpdate(unittest.TestCase):
    """PatchedGenericAssetUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedGenericAssetUpdate:
        """Test PatchedGenericAssetUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedGenericAssetUpdate`
        """
        model = PatchedGenericAssetUpdate()  # noqa: E501
        if include_optional:
            return PatchedGenericAssetUpdate(
                is_uploaded = True
            )
        else:
            return PatchedGenericAssetUpdate(
        )
        """

    def testPatchedGenericAssetUpdate(self):
        """Test PatchedGenericAssetUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
