# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.create_issue_comment_request import CreateIssueCommentRequest  # noqa: E501

class TestCreateIssueCommentRequest(unittest.TestCase):
    """CreateIssueCommentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIssueCommentRequest:
        """Test CreateIssueCommentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIssueCommentRequest`
        """
        model = CreateIssueCommentRequest()  # noqa: E501
        if include_optional:
            return CreateIssueCommentRequest(
                comment_html = ''
            )
        else:
            return CreateIssueCommentRequest(
                comment_html = '',
        )
        """

    def testCreateIssueCommentRequest(self):
        """Test CreateIssueCommentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
