# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.create_intake_issue_request_issue_issue import CreateIntakeIssueRequestIssueIssue  # noqa: E501

class TestCreateIntakeIssueRequestIssueIssue(unittest.TestCase):
    """CreateIntakeIssueRequestIssueIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIntakeIssueRequestIssueIssue:
        """Test CreateIntakeIssueRequestIssueIssue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIntakeIssueRequestIssueIssue`
        """
        model = CreateIntakeIssueRequestIssueIssue()  # noqa: E501
        if include_optional:
            return CreateIntakeIssueRequestIssueIssue(
                name = 'Issue 1',
                description_html = '<p>This is an issue description</p>',
                priority = 'low'
            )
        else:
            return CreateIntakeIssueRequestIssueIssue(
        )
        """

    def testCreateIntakeIssueRequestIssueIssue(self):
        """Test CreateIntakeIssueRequestIssueIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
