# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.create_module_request import CreateModuleRequest  # noqa: E501

class TestCreateModuleRequest(unittest.TestCase):
    """CreateModuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateModuleRequest:
        """Test CreateModuleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateModuleRequest`
        """
        model = CreateModuleRequest()  # noqa: E501
        if include_optional:
            return CreateModuleRequest(
                name = 'Module 1',
                description = 'This is a module description',
                start_date = '2025-01-01T00:00Z',
                target_date = '2025-01-01T00:00Z',
                status = 'planned',
                lead = '123e4567-e89b-12d3-a456-426614174000',
                members = [
                    ''
                    ]
            )
        else:
            return CreateModuleRequest(
        )
        """

    def testCreateModuleRequest(self):
        """Test CreateModuleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
