# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.issue_activity import IssueActivity  # noqa: E501

class TestIssueActivity(unittest.TestCase):
    """IssueActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueActivity:
        """Test IssueActivity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssueActivity`
        """
        model = IssueActivity()  # noqa: E501
        if include_optional:
            return IssueActivity(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verb = '',
                field = '',
                old_value = '',
                new_value = '',
                comment = '',
                attachments = [
                    ''
                    ],
                old_identifier = '',
                new_identifier = '',
                epoch = 1.337,
                project = '',
                workspace = '',
                issue = '',
                issue_comment = '',
                actor = ''
            )
        else:
            return IssueActivity(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                project = '',
                workspace = '',
        )
        """

    def testIssueActivity(self):
        """Test IssueActivity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
