# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.general_api import GeneralApi  # noqa: E501


class TestGeneralApi(unittest.TestCase):
    """GeneralApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GeneralApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_search_issues(self) -> None:
        """Test case for search_issues

        Search issues  # noqa: E501
        """
        pass

    def test_workspaces_issues_retrieve(self) -> None:
        """Test case for workspaces_issues_retrieve

        Retrieve Issues  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
