# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.create_intake_issue_request_issue import CreateIntakeIssueRequestIssue  # noqa: E501

class TestCreateIntakeIssueRequestIssue(unittest.TestCase):
    """CreateIntakeIssueRequestIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIntakeIssueRequestIssue:
        """Test CreateIntakeIssueRequestIssue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIntakeIssueRequestIssue`
        """
        model = CreateIntakeIssueRequestIssue()  # noqa: E501
        if include_optional:
            return CreateIntakeIssueRequestIssue(
                issue = plane.models.create_intake_issue_request_issue_issue.create_intake_issue_request_issue_issue(
                    name = 'Issue 1', 
                    description_html = '<p>This is an issue description</p>', 
                    priority = 'low', )
            )
        else:
            return CreateIntakeIssueRequestIssue(
        )
        """

    def testCreateIntakeIssueRequestIssue(self):
        """Test CreateIntakeIssueRequestIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
