# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plane.api.members_api import MembersApi  # noqa: E501


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_project_members(self) -> None:
        """Test case for get_project_members

        Get all the users that are present inside the project  # noqa: E501
        """
        pass

    def test_get_workspace_members(self) -> None:
        """Test case for get_workspace_members

        Get all the users that are present inside the workspace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
