# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr

class CreateCycleRequest(BaseModel):
    """
    CreateCycleRequest
    """
    name: constr(strict=True, max_length=255) = Field(default=..., description="Cycle Name")
    description: Optional[StrictStr] = Field(default=None, description="Cycle Description")
    start_date: Optional[datetime] = Field(default=None, description="Start Date")
    end_date: Optional[datetime] = Field(default=None, description="End Date")
    __properties = ["name", "description", "start_date", "end_date"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateCycleRequest:
        """Create an instance of CreateCycleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if start_date (nullable) is None
        # and __fields_set__ contains the field
        if self.start_date is None and "start_date" in self.__fields_set__:
            _dict['start_date'] = None

        # set to None if end_date (nullable) is None
        # and __fields_set__ contains the field
        if self.end_date is None and "end_date" in self.__fields_set__:
            _dict['end_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateCycleRequest:
        """Create an instance of CreateCycleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateCycleRequest.parse_obj(obj)

        _obj = CreateCycleRequest.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date")
        })
        return _obj


