# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr

class LabelLite(BaseModel):
    """
    LabelLite
    """
    id: StrictStr = Field(...)
    name: constr(strict=True, max_length=255) = Field(...)
    color: Optional[constr(strict=True, max_length=255)] = None
    __properties = ["id", "name", "color"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LabelLite:
        """Create an instance of LabelLite from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LabelLite:
        """Create an instance of LabelLite from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LabelLite.parse_obj(obj)

        _obj = LabelLite.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "color": obj.get("color")
        })
        return _obj


