# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool

class PatchedGenericAssetUpdate(BaseModel):
    """
    Serializer for generic asset update requests  # noqa: E501
    """
    is_uploaded: Optional[StrictBool] = Field(default=True, description="Whether the asset has been successfully uploaded")
    __properties = ["is_uploaded"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PatchedGenericAssetUpdate:
        """Create an instance of PatchedGenericAssetUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PatchedGenericAssetUpdate:
        """Create an instance of PatchedGenericAssetUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PatchedGenericAssetUpdate.parse_obj(obj)

        _obj = PatchedGenericAssetUpdate.parse_obj({
            "is_uploaded": obj.get("is_uploaded") if obj.get("is_uploaded") is not None else True
        })
        return _obj


