# coding: utf-8

"""
    Plane API

    Plane External API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator

class StateLite(BaseModel):
    """
    StateLite
    """
    id: StrictStr = Field(...)
    name: StrictStr = Field(...)
    color: StrictStr = Field(...)
    group: StrictStr = Field(default=..., description="* `backlog` - Backlog * `unstarted` - Unstarted * `started` - Started * `completed` - Completed * `cancelled` - Cancelled * `triage` - Triage")
    __properties = ["id", "name", "color", "group"]

    @validator('group')
    def group_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('backlog', 'unstarted', 'started', 'completed', 'cancelled', 'triage',):
            raise ValueError("must be one of enum values ('backlog', 'unstarted', 'started', 'completed', 'cancelled', 'triage')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StateLite:
        """Create an instance of StateLite from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "name",
                            "color",
                            "group",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StateLite:
        """Create an instance of StateLite from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StateLite.parse_obj(obj)

        _obj = StateLite.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "color": obj.get("color"),
            "group": obj.get("group")
        })
        return _obj


