# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class EntityTypeEnum(str, Enum):
    """
    * `ISSUE_ATTACHMENT` - Issue Attachment * `ISSUE_DESCRIPTION` - Issue Description * `COMMENT_DESCRIPTION` - Comment Description * `PAGE_DESCRIPTION` - Page Description * `USER_COVER` - User Cover * `USER_AVATAR` - User Avatar * `WORKSPACE_LOGO` - Workspace Logo * `PROJECT_COVER` - Project Cover * `DRAFT_ISSUE_ATTACHMENT` - Draft Issue Attachment * `DRAFT_ISSUE_DESCRIPTION` - Draft Issue Description
    """

    """
    allowed enum values
    """
    ISSUE_ATTACHMENT = 'ISSUE_ATTACHMENT'
    ISSUE_DESCRIPTION = 'ISSUE_DESCRIPTION'
    COMMENT_DESCRIPTION = 'COMMENT_DESCRIPTION'
    PAGE_DESCRIPTION = 'PAGE_DESCRIPTION'
    USER_COVER = 'USER_COVER'
    USER_AVATAR = 'USER_AVATAR'
    WORKSPACE_LOGO = 'WORKSPACE_LOGO'
    PROJECT_COVER = 'PROJECT_COVER'
    DRAFT_ISSUE_ATTACHMENT = 'DRAFT_ISSUE_ATTACHMENT'
    DRAFT_ISSUE_DESCRIPTION = 'DRAFT_ISSUE_DESCRIPTION'

    @classmethod
    def from_json(cls, json_str: str) -> EntityTypeEnum:
        """Create an instance of EntityTypeEnum from a JSON string"""
        return EntityTypeEnum(json.loads(json_str))


