# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class GroupEnum(str, Enum):
    """
    * `backlog` - Backlog * `unstarted` - Unstarted * `started` - Started * `completed` - Completed * `cancelled` - Cancelled * `triage` - Triage
    """

    """
    allowed enum values
    """
    BACKLOG = 'backlog'
    UNSTARTED = 'unstarted'
    STARTED = 'started'
    COMPLETED = 'completed'
    CANCELLED = 'cancelled'
    TRIAGE = 'triage'

    @classmethod
    def from_json(cls, json_str: str) -> GroupEnum:
        """Create an instance of GroupEnum from a JSON string"""
        return GroupEnum(json.loads(json_str))


