# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr
from plane.models.inbox_issue_status_enum import InboxIssueStatusEnum
from plane.models.issue_expand import IssueExpand

class InboxIssue(BaseModel):
    """
    InboxIssue
    """
    created_at: datetime = Field(...)
    created_by: Optional[StrictStr] = Field(...)
    deleted_at: Optional[datetime] = None
    duplicate_to: Optional[StrictStr] = None
    external_id: Optional[constr(strict=True, max_length=255)] = None
    external_source: Optional[constr(strict=True, max_length=255)] = None
    id: StrictStr = Field(...)
    inbox: StrictStr = Field(...)
    issue: StrictStr = Field(...)
    issue_detail: IssueExpand = Field(...)
    project: StrictStr = Field(...)
    snoozed_till: Optional[datetime] = None
    source: Optional[StrictStr] = None
    status: Optional[InboxIssueStatusEnum] = None
    updated_at: datetime = Field(...)
    updated_by: Optional[StrictStr] = Field(...)
    workspace: StrictStr = Field(...)
    __properties = ["created_at", "created_by", "deleted_at", "duplicate_to", "external_id", "external_source", "id", "inbox", "issue", "issue_detail", "project", "snoozed_till", "source", "status", "updated_at", "updated_by", "workspace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InboxIssue:
        """Create an instance of InboxIssue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "created_at",
                            "created_by",
                            "id",
                            "issue",
                            "issue_detail",
                            "project",
                            "updated_at",
                            "updated_by",
                            "workspace",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of issue_detail
        if self.issue_detail:
            _dict['issue_detail'] = self.issue_detail.to_dict()
        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if deleted_at (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted_at is None and "deleted_at" in self.__fields_set__:
            _dict['deleted_at'] = None

        # set to None if duplicate_to (nullable) is None
        # and __fields_set__ contains the field
        if self.duplicate_to is None and "duplicate_to" in self.__fields_set__:
            _dict['duplicate_to'] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict['external_id'] = None

        # set to None if external_source (nullable) is None
        # and __fields_set__ contains the field
        if self.external_source is None and "external_source" in self.__fields_set__:
            _dict['external_source'] = None

        # set to None if snoozed_till (nullable) is None
        # and __fields_set__ contains the field
        if self.snoozed_till is None and "snoozed_till" in self.__fields_set__:
            _dict['snoozed_till'] = None

        # set to None if source (nullable) is None
        # and __fields_set__ contains the field
        if self.source is None and "source" in self.__fields_set__:
            _dict['source'] = None

        # set to None if updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.updated_by is None and "updated_by" in self.__fields_set__:
            _dict['updated_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InboxIssue:
        """Create an instance of InboxIssue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InboxIssue.parse_obj(obj)

        _obj = InboxIssue.parse_obj({
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "deleted_at": obj.get("deleted_at"),
            "duplicate_to": obj.get("duplicate_to"),
            "external_id": obj.get("external_id"),
            "external_source": obj.get("external_source"),
            "id": obj.get("id"),
            "inbox": obj.get("inbox"),
            "issue": obj.get("issue"),
            "issue_detail": IssueExpand.from_dict(obj.get("issue_detail")) if obj.get("issue_detail") is not None else None,
            "project": obj.get("project"),
            "snoozed_till": obj.get("snoozed_till"),
            "source": obj.get("source"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "workspace": obj.get("workspace")
        })
        return _obj


