# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Any, List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictBytes, StrictFloat, StrictInt, StrictStr, conint, conlist, constr
from plane.models.cycle_lite import CycleLite
from plane.models.label_lite import LabelLite
from plane.models.module_lite import ModuleLite
from plane.models.priority_enum import PriorityEnum
from plane.models.state_lite import StateLite
from plane.models.user_lite import UserLite

class IssueExpand(BaseModel):
    """
    IssueExpand
    """
    archived_at: Optional[date] = None
    assignees: conlist(UserLite) = Field(...)
    completed_at: Optional[datetime] = None
    created_at: datetime = Field(...)
    created_by: Optional[StrictStr] = Field(...)
    cycle: CycleLite = Field(...)
    deleted_at: Optional[datetime] = None
    description: Optional[Any] = None
    description_binary: Optional[Union[StrictBytes, StrictStr]] = Field(...)
    description_html: Optional[StrictStr] = None
    description_stripped: Optional[StrictStr] = None
    estimate_point: Optional[StrictStr] = None
    external_id: Optional[constr(strict=True, max_length=255)] = None
    external_source: Optional[constr(strict=True, max_length=255)] = None
    id: StrictStr = Field(...)
    is_draft: Optional[StrictBool] = None
    labels: conlist(LabelLite) = Field(...)
    module: ModuleLite = Field(...)
    name: constr(strict=True, max_length=255) = Field(...)
    parent: Optional[StrictStr] = None
    point: Optional[conint(strict=True, le=12, ge=0)] = None
    priority: Optional[PriorityEnum] = None
    project: StrictStr = Field(...)
    sequence_id: Optional[conint(strict=True, le=2147483647, ge=-2147483648)] = None
    sort_order: Optional[Union[StrictFloat, StrictInt]] = None
    start_date: Optional[date] = None
    state: StateLite = Field(...)
    target_date: Optional[date] = None
    type: Optional[StrictStr] = None
    updated_at: datetime = Field(...)
    updated_by: Optional[StrictStr] = Field(...)
    workspace: StrictStr = Field(...)
    __properties = ["archived_at", "assignees", "completed_at", "created_at", "created_by", "cycle", "deleted_at", "description", "description_binary", "description_html", "description_stripped", "estimate_point", "external_id", "external_source", "id", "is_draft", "labels", "module", "name", "parent", "point", "priority", "project", "sequence_id", "sort_order", "start_date", "state", "target_date", "type", "updated_at", "updated_by", "workspace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IssueExpand:
        """Create an instance of IssueExpand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "assignees",
                            "created_at",
                            "created_by",
                            "cycle",
                            "description_binary",
                            "id",
                            "labels",
                            "module",
                            "project",
                            "state",
                            "updated_at",
                            "updated_by",
                            "workspace",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in assignees (list)
        _items = []
        if self.assignees:
            for _item in self.assignees:
                if _item:
                    _items.append(_item.to_dict())
            _dict['assignees'] = _items
        # override the default output from pydantic by calling `to_dict()` of cycle
        if self.cycle:
            _dict['cycle'] = self.cycle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item in self.labels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of module
        if self.module:
            _dict['module'] = self.module.to_dict()
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        # set to None if archived_at (nullable) is None
        # and __fields_set__ contains the field
        if self.archived_at is None and "archived_at" in self.__fields_set__:
            _dict['archived_at'] = None

        # set to None if completed_at (nullable) is None
        # and __fields_set__ contains the field
        if self.completed_at is None and "completed_at" in self.__fields_set__:
            _dict['completed_at'] = None

        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if deleted_at (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted_at is None and "deleted_at" in self.__fields_set__:
            _dict['deleted_at'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if description_binary (nullable) is None
        # and __fields_set__ contains the field
        if self.description_binary is None and "description_binary" in self.__fields_set__:
            _dict['description_binary'] = None

        # set to None if description_stripped (nullable) is None
        # and __fields_set__ contains the field
        if self.description_stripped is None and "description_stripped" in self.__fields_set__:
            _dict['description_stripped'] = None

        # set to None if estimate_point (nullable) is None
        # and __fields_set__ contains the field
        if self.estimate_point is None and "estimate_point" in self.__fields_set__:
            _dict['estimate_point'] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict['external_id'] = None

        # set to None if external_source (nullable) is None
        # and __fields_set__ contains the field
        if self.external_source is None and "external_source" in self.__fields_set__:
            _dict['external_source'] = None

        # set to None if parent (nullable) is None
        # and __fields_set__ contains the field
        if self.parent is None and "parent" in self.__fields_set__:
            _dict['parent'] = None

        # set to None if point (nullable) is None
        # and __fields_set__ contains the field
        if self.point is None and "point" in self.__fields_set__:
            _dict['point'] = None

        # set to None if start_date (nullable) is None
        # and __fields_set__ contains the field
        if self.start_date is None and "start_date" in self.__fields_set__:
            _dict['start_date'] = None

        # set to None if target_date (nullable) is None
        # and __fields_set__ contains the field
        if self.target_date is None and "target_date" in self.__fields_set__:
            _dict['target_date'] = None

        # set to None if type (nullable) is None
        # and __fields_set__ contains the field
        if self.type is None and "type" in self.__fields_set__:
            _dict['type'] = None

        # set to None if updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.updated_by is None and "updated_by" in self.__fields_set__:
            _dict['updated_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IssueExpand:
        """Create an instance of IssueExpand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IssueExpand.parse_obj(obj)

        _obj = IssueExpand.parse_obj({
            "archived_at": obj.get("archived_at"),
            "assignees": [UserLite.from_dict(_item) for _item in obj.get("assignees")] if obj.get("assignees") is not None else None,
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "cycle": CycleLite.from_dict(obj.get("cycle")) if obj.get("cycle") is not None else None,
            "deleted_at": obj.get("deleted_at"),
            "description": obj.get("description"),
            "description_binary": obj.get("description_binary"),
            "description_html": obj.get("description_html"),
            "description_stripped": obj.get("description_stripped"),
            "estimate_point": obj.get("estimate_point"),
            "external_id": obj.get("external_id"),
            "external_source": obj.get("external_source"),
            "id": obj.get("id"),
            "is_draft": obj.get("is_draft"),
            "labels": [LabelLite.from_dict(_item) for _item in obj.get("labels")] if obj.get("labels") is not None else None,
            "module": ModuleLite.from_dict(obj.get("module")) if obj.get("module") is not None else None,
            "name": obj.get("name"),
            "parent": obj.get("parent"),
            "point": obj.get("point"),
            "priority": obj.get("priority"),
            "project": obj.get("project"),
            "sequence_id": obj.get("sequence_id"),
            "sort_order": obj.get("sort_order"),
            "start_date": obj.get("start_date"),
            "state": StateLite.from_dict(obj.get("state")) if obj.get("state") is not None else None,
            "target_date": obj.get("target_date"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "workspace": obj.get("workspace")
        })
        return _obj


