# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, constr

class IssuePropertyValueAPI(BaseModel):
    """
    IssuePropertyValueAPI
    """
    created_at: datetime = Field(...)
    created_by: Optional[StrictStr] = Field(...)
    deleted_at: Optional[datetime] = Field(...)
    external_id: Optional[constr(strict=True, max_length=255)] = None
    external_source: Optional[constr(strict=True, max_length=255)] = None
    id: StrictStr = Field(...)
    issue: StrictStr = Field(...)
    project: Optional[StrictStr] = Field(...)
    var_property: StrictStr = Field(default=..., alias="property")
    updated_at: datetime = Field(...)
    updated_by: Optional[StrictStr] = Field(...)
    value_boolean: Optional[StrictBool] = None
    value_datetime: Optional[datetime] = None
    value_decimal: Optional[Union[StrictFloat, StrictInt]] = None
    value_option: Optional[StrictStr] = None
    value_text: Optional[StrictStr] = None
    value_uuid: Optional[StrictStr] = None
    workspace: StrictStr = Field(...)
    __properties = ["created_at", "created_by", "deleted_at", "external_id", "external_source", "id", "issue", "project", "property", "updated_at", "updated_by", "value_boolean", "value_datetime", "value_decimal", "value_option", "value_text", "value_uuid", "workspace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IssuePropertyValueAPI:
        """Create an instance of IssuePropertyValueAPI from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "created_at",
                            "created_by",
                            "deleted_at",
                            "id",
                            "project",
                            "updated_at",
                            "updated_by",
                            "workspace",
                          },
                          exclude_none=True)
        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if deleted_at (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted_at is None and "deleted_at" in self.__fields_set__:
            _dict['deleted_at'] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict['external_id'] = None

        # set to None if external_source (nullable) is None
        # and __fields_set__ contains the field
        if self.external_source is None and "external_source" in self.__fields_set__:
            _dict['external_source'] = None

        # set to None if project (nullable) is None
        # and __fields_set__ contains the field
        if self.project is None and "project" in self.__fields_set__:
            _dict['project'] = None

        # set to None if updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.updated_by is None and "updated_by" in self.__fields_set__:
            _dict['updated_by'] = None

        # set to None if value_datetime (nullable) is None
        # and __fields_set__ contains the field
        if self.value_datetime is None and "value_datetime" in self.__fields_set__:
            _dict['value_datetime'] = None

        # set to None if value_option (nullable) is None
        # and __fields_set__ contains the field
        if self.value_option is None and "value_option" in self.__fields_set__:
            _dict['value_option'] = None

        # set to None if value_uuid (nullable) is None
        # and __fields_set__ contains the field
        if self.value_uuid is None and "value_uuid" in self.__fields_set__:
            _dict['value_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IssuePropertyValueAPI:
        """Create an instance of IssuePropertyValueAPI from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IssuePropertyValueAPI.parse_obj(obj)

        _obj = IssuePropertyValueAPI.parse_obj({
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "deleted_at": obj.get("deleted_at"),
            "external_id": obj.get("external_id"),
            "external_source": obj.get("external_source"),
            "id": obj.get("id"),
            "issue": obj.get("issue"),
            "project": obj.get("project"),
            "var_property": obj.get("property"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "value_boolean": obj.get("value_boolean"),
            "value_datetime": obj.get("value_datetime"),
            "value_decimal": obj.get("value_decimal"),
            "value_option": obj.get("value_option"),
            "value_text": obj.get("value_text"),
            "value_uuid": obj.get("value_uuid"),
            "workspace": obj.get("workspace")
        })
        return _obj


