# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, constr
from plane.models.issue_attachment_entity_type import IssueAttachmentEntityType

class IssueAttachment(BaseModel):
    """
    IssueAttachment
    """
    asset: StrictStr = Field(...)
    attributes: Optional[Any] = None
    comment: Optional[StrictStr] = None
    created_at: datetime = Field(...)
    created_by: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = None
    draft_issue: Optional[StrictStr] = None
    entity_type: Optional[IssueAttachmentEntityType] = None
    external_id: Optional[constr(strict=True, max_length=255)] = None
    external_source: Optional[constr(strict=True, max_length=255)] = None
    id: StrictStr = Field(...)
    is_archived: Optional[StrictBool] = None
    is_deleted: Optional[StrictBool] = None
    is_uploaded: Optional[StrictBool] = None
    issue: Optional[StrictStr] = Field(...)
    page: Optional[StrictStr] = None
    project: Optional[StrictStr] = Field(...)
    size: Optional[Union[StrictFloat, StrictInt]] = None
    storage_metadata: Optional[Any] = None
    updated_at: datetime = Field(...)
    updated_by: Optional[StrictStr] = Field(...)
    user: Optional[StrictStr] = None
    workspace: Optional[StrictStr] = Field(...)
    __properties = ["asset", "attributes", "comment", "created_at", "created_by", "deleted_at", "draft_issue", "entity_type", "external_id", "external_source", "id", "is_archived", "is_deleted", "is_uploaded", "issue", "page", "project", "size", "storage_metadata", "updated_at", "updated_by", "user", "workspace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IssueAttachment:
        """Create an instance of IssueAttachment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "created_at",
                            "id",
                            "issue",
                            "project",
                            "updated_at",
                            "updated_by",
                            "workspace",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of entity_type
        if self.entity_type:
            _dict['entity_type'] = self.entity_type.to_dict()
        # set to None if attributes (nullable) is None
        # and __fields_set__ contains the field
        if self.attributes is None and "attributes" in self.__fields_set__:
            _dict['attributes'] = None

        # set to None if comment (nullable) is None
        # and __fields_set__ contains the field
        if self.comment is None and "comment" in self.__fields_set__:
            _dict['comment'] = None

        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if deleted_at (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted_at is None and "deleted_at" in self.__fields_set__:
            _dict['deleted_at'] = None

        # set to None if draft_issue (nullable) is None
        # and __fields_set__ contains the field
        if self.draft_issue is None and "draft_issue" in self.__fields_set__:
            _dict['draft_issue'] = None

        # set to None if entity_type (nullable) is None
        # and __fields_set__ contains the field
        if self.entity_type is None and "entity_type" in self.__fields_set__:
            _dict['entity_type'] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict['external_id'] = None

        # set to None if external_source (nullable) is None
        # and __fields_set__ contains the field
        if self.external_source is None and "external_source" in self.__fields_set__:
            _dict['external_source'] = None

        # set to None if issue (nullable) is None
        # and __fields_set__ contains the field
        if self.issue is None and "issue" in self.__fields_set__:
            _dict['issue'] = None

        # set to None if page (nullable) is None
        # and __fields_set__ contains the field
        if self.page is None and "page" in self.__fields_set__:
            _dict['page'] = None

        # set to None if project (nullable) is None
        # and __fields_set__ contains the field
        if self.project is None and "project" in self.__fields_set__:
            _dict['project'] = None

        # set to None if storage_metadata (nullable) is None
        # and __fields_set__ contains the field
        if self.storage_metadata is None and "storage_metadata" in self.__fields_set__:
            _dict['storage_metadata'] = None

        # set to None if updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.updated_by is None and "updated_by" in self.__fields_set__:
            _dict['updated_by'] = None

        # set to None if user (nullable) is None
        # and __fields_set__ contains the field
        if self.user is None and "user" in self.__fields_set__:
            _dict['user'] = None

        # set to None if workspace (nullable) is None
        # and __fields_set__ contains the field
        if self.workspace is None and "workspace" in self.__fields_set__:
            _dict['workspace'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IssueAttachment:
        """Create an instance of IssueAttachment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IssueAttachment.parse_obj(obj)

        _obj = IssueAttachment.parse_obj({
            "asset": obj.get("asset"),
            "attributes": obj.get("attributes"),
            "comment": obj.get("comment"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "deleted_at": obj.get("deleted_at"),
            "draft_issue": obj.get("draft_issue"),
            "entity_type": IssueAttachmentEntityType.from_dict(obj.get("entity_type")) if obj.get("entity_type") is not None else None,
            "external_id": obj.get("external_id"),
            "external_source": obj.get("external_source"),
            "id": obj.get("id"),
            "is_archived": obj.get("is_archived"),
            "is_deleted": obj.get("is_deleted"),
            "is_uploaded": obj.get("is_uploaded"),
            "issue": obj.get("issue"),
            "page": obj.get("page"),
            "project": obj.get("project"),
            "size": obj.get("size"),
            "storage_metadata": obj.get("storage_metadata"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "user": obj.get("user"),
            "workspace": obj.get("workspace")
        })
        return _obj


