# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, constr

class PatchedIssuePropertyOptionAPI(BaseModel):
    """
    PatchedIssuePropertyOptionAPI
    """
    created_at: Optional[datetime] = None
    created_by: Optional[StrictStr] = None
    deleted_at: Optional[datetime] = None
    description: Optional[StrictStr] = None
    external_id: Optional[constr(strict=True, max_length=255)] = None
    external_source: Optional[constr(strict=True, max_length=255)] = None
    id: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = None
    is_default: Optional[StrictBool] = None
    logo_props: Optional[Any] = None
    name: Optional[constr(strict=True, max_length=255)] = None
    parent: Optional[StrictStr] = None
    project: Optional[StrictStr] = None
    var_property: Optional[StrictStr] = Field(default=None, alias="property")
    sort_order: Optional[Union[StrictFloat, StrictInt]] = None
    updated_at: Optional[datetime] = None
    updated_by: Optional[StrictStr] = None
    workspace: Optional[StrictStr] = None
    __properties = ["created_at", "created_by", "deleted_at", "description", "external_id", "external_source", "id", "is_active", "is_default", "logo_props", "name", "parent", "project", "property", "sort_order", "updated_at", "updated_by", "workspace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PatchedIssuePropertyOptionAPI:
        """Create an instance of PatchedIssuePropertyOptionAPI from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "created_at",
                            "created_by",
                            "deleted_at",
                            "id",
                            "logo_props",
                            "project",
                            "var_property",
                            "sort_order",
                            "updated_at",
                            "updated_by",
                            "workspace",
                          },
                          exclude_none=True)
        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if deleted_at (nullable) is None
        # and __fields_set__ contains the field
        if self.deleted_at is None and "deleted_at" in self.__fields_set__:
            _dict['deleted_at'] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict['external_id'] = None

        # set to None if external_source (nullable) is None
        # and __fields_set__ contains the field
        if self.external_source is None and "external_source" in self.__fields_set__:
            _dict['external_source'] = None

        # set to None if logo_props (nullable) is None
        # and __fields_set__ contains the field
        if self.logo_props is None and "logo_props" in self.__fields_set__:
            _dict['logo_props'] = None

        # set to None if parent (nullable) is None
        # and __fields_set__ contains the field
        if self.parent is None and "parent" in self.__fields_set__:
            _dict['parent'] = None

        # set to None if project (nullable) is None
        # and __fields_set__ contains the field
        if self.project is None and "project" in self.__fields_set__:
            _dict['project'] = None

        # set to None if updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.updated_by is None and "updated_by" in self.__fields_set__:
            _dict['updated_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PatchedIssuePropertyOptionAPI:
        """Create an instance of PatchedIssuePropertyOptionAPI from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PatchedIssuePropertyOptionAPI.parse_obj(obj)

        _obj = PatchedIssuePropertyOptionAPI.parse_obj({
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "deleted_at": obj.get("deleted_at"),
            "description": obj.get("description"),
            "external_id": obj.get("external_id"),
            "external_source": obj.get("external_source"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "is_default": obj.get("is_default"),
            "logo_props": obj.get("logo_props"),
            "name": obj.get("name"),
            "parent": obj.get("parent"),
            "project": obj.get("project"),
            "var_property": obj.get("property"),
            "sort_order": obj.get("sort_order"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "workspace": obj.get("workspace")
        })
        return _obj


