# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.patched_cycle import PatchedCycle  # noqa: E501

class TestPatchedCycle(unittest.TestCase):
    """PatchedCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedCycle:
        """Test PatchedCycle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedCycle`
        """
        model = PatchedCycle()  # noqa: E501
        if include_optional:
            return PatchedCycle(
                archived_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                backlog_issues = 56,
                cancelled_issues = 56,
                completed_estimates = 1.337,
                completed_issues = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                external_id = '',
                external_source = '',
                id = '',
                logo_props = None,
                name = '',
                owned_by = '',
                progress_snapshot = None,
                project = '',
                sort_order = 1.337,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_estimates = 1.337,
                started_issues = 56,
                timezone = 'Africa/Abidjan',
                total_estimates = 1.337,
                total_issues = 56,
                unstarted_issues = 56,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                version = -2147483648,
                view_props = None,
                workspace = ''
            )
        else:
            return PatchedCycle(
        )
        """

    def testPatchedCycle(self):
        """Test PatchedCycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
