# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.user_lite import UserLite  # noqa: E501

class TestUserLite(unittest.TestCase):
    """UserLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserLite:
        """Test UserLite
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserLite`
        """
        model = UserLite()  # noqa: E501
        if include_optional:
            return UserLite(
                avatar = '',
                avatar_url = '',
                display_name = '',
                email = '',
                first_name = '',
                id = '',
                last_name = ''
            )
        else:
            return UserLite(
                avatar = '',
                avatar_url = '',
                display_name = '',
                email = '',
                first_name = '',
                id = '',
                last_name = '',
        )
        """

    def testUserLite(self):
        """Test UserLite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
