# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.property_type_enum import PropertyTypeEnum  # noqa: E501

class TestPropertyTypeEnum(unittest.TestCase):
    """PropertyTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertyTypeEnum(self):
        """Test PropertyTypeEnum"""
        # inst = PropertyTypeEnum()

if __name__ == '__main__':
    unittest.main()
