# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.group_enum import GroupEnum  # noqa: E501

class TestGroupEnum(unittest.TestCase):
    """GroupEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupEnum(self):
        """Test GroupEnum"""
        # inst = GroupEnum()

if __name__ == '__main__':
    unittest.main()
