# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.patched_project import PatchedProject  # noqa: E501

class TestPatchedProject(unittest.TestCase):
    """PatchedProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedProject:
        """Test PatchedProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedProject`
        """
        model = PatchedProject()  # noqa: E501
        if include_optional:
            return PatchedProject(
                archive_in = 0,
                archived_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                close_in = 0,
                cover_image = '',
                cover_image_asset = '',
                cover_image_url = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                cycle_view = True,
                default_assignee = '',
                default_state = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                description_html = None,
                description_text = None,
                emoji = '',
                estimate = '',
                guest_view_all_features = True,
                icon_prop = None,
                id = '',
                identifier = '',
                inbox_view = True,
                is_deployed = True,
                is_issue_type_enabled = True,
                is_member = True,
                is_time_tracking_enabled = True,
                issue_views_view = True,
                logo_props = None,
                member_role = 56,
                module_view = True,
                name = '',
                network = 0,
                page_view = True,
                project_lead = '',
                sort_order = 1.337,
                timezone = 'Africa/Abidjan',
                total_cycles = 56,
                total_members = 56,
                total_modules = 56,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                workspace = ''
            )
        else:
            return PatchedProject(
        )
        """

    def testPatchedProject(self):
        """Test PatchedProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
