# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.state_lite import StateLite  # noqa: E501

class TestStateLite(unittest.TestCase):
    """StateLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateLite:
        """Test StateLite
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateLite`
        """
        model = StateLite()  # noqa: E501
        if include_optional:
            return StateLite(
                color = '',
                group = 'backlog',
                id = '',
                name = ''
            )
        else:
            return StateLite(
                color = '',
                group = 'backlog',
                id = '',
                name = '',
        )
        """

    def testStateLite(self):
        """Test StateLite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
