# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.network_enum import NetworkEnum  # noqa: E501

class TestNetworkEnum(unittest.TestCase):
    """NetworkEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkEnum(self):
        """Test NetworkEnum"""
        # inst = NetworkEnum()

if __name__ == '__main__':
    unittest.main()
