# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.label_lite import LabelLite  # noqa: E501

class TestLabelLite(unittest.TestCase):
    """LabelLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LabelLite:
        """Test LabelLite
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LabelLite`
        """
        model = LabelLite()  # noqa: E501
        if include_optional:
            return LabelLite(
                color = '',
                id = '',
                name = ''
            )
        else:
            return LabelLite(
                id = '',
                name = '',
        )
        """

    def testLabelLite(self):
        """Test LabelLite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
