# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.issue_property_api import IssuePropertyAPI  # noqa: E501

class TestIssuePropertyAPI(unittest.TestCase):
    """IssuePropertyAPI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssuePropertyAPI:
        """Test IssuePropertyAPI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssuePropertyAPI`
        """
        model = IssuePropertyAPI()  # noqa: E501
        if include_optional:
            return IssuePropertyAPI(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                default_value = [
                    ''
                    ],
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                display_name = '',
                external_id = '',
                external_source = '',
                id = '',
                is_active = True,
                is_multi = True,
                is_required = True,
                issue_type = '',
                logo_props = None,
                name = '',
                project = '',
                property_type = 'TEXT',
                relation_type = None,
                settings = None,
                sort_order = 1.337,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                validation_rules = None,
                workspace = ''
            )
        else:
            return IssuePropertyAPI(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                display_name = '',
                id = '',
                issue_type = '',
                logo_props = None,
                name = '',
                project = '',
                property_type = 'TEXT',
                settings = None,
                sort_order = 1.337,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                workspace = '',
        )
        """

    def testIssuePropertyAPI(self):
        """Test IssuePropertyAPI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
