# coding: utf-8

"""
    Plane API

    API documentation for my specific app

    The version of the OpenAPI document: 1.0.0 (1.0.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from plane.models.issue_attachment import IssueAttachment  # noqa: E501

class TestIssueAttachment(unittest.TestCase):
    """IssueAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueAttachment:
        """Test IssueAttachment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssueAttachment`
        """
        model = IssueAttachment()  # noqa: E501
        if include_optional:
            return IssueAttachment(
                asset = '',
                attributes = None,
                comment = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                draft_issue = '',
                entity_type = None,
                external_id = '',
                external_source = '',
                id = '',
                is_archived = True,
                is_deleted = True,
                is_uploaded = True,
                issue = '',
                page = '',
                project = '',
                size = 1.337,
                storage_metadata = None,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                user = '',
                workspace = ''
            )
        else:
            return IssueAttachment(
                asset = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                issue = '',
                project = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                workspace = '',
        )
        """

    def testIssueAttachment(self):
        """Test IssueAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
